/* =====================================================================
   TRIP DATA — Bangkok & Chiang Rai · 14–21 November 2026
   Hand-authored itinerary model. Coordinates are best-effort; a few
   lesser-known spots are flagged `approx:true` and shown with a hint.
   Each stop carries an estimated `time` and links out to an Instagram
   hashtag so you can preview the place.
   ===================================================================== */

const TRIP = {
  id: "bangkok-2026",
  title: "Bangkok & Chiang Rai",
  subtitle: "An 8-day journey through temples, markets & street feasts",
  startISO: "2026-11-14",
  endISO: "2026-11-21",
  cover: "img/bangkok.png",
  travellers: "Antonio & companions",
};

/* Other journeys shown on the dashboard (itinerary not built yet). */
const OTHER_TRIPS = [
  {
    id: "taiwan-2027",
    title: "Taiwan Escape",
    dateLabel: "19 Feb – 1 Mar 2027",
    subtitle: "A journey through night markets, mountains & modern marvels.",
    cover: "img/taiwan.png",
    comingSoon: true,
  },
];

/* Category metadata: color + emoji marker + label */
const CATS = {
  temple:    { label: "Temple",     color: "#e6b450", icon: "🛕" },
  shopping:  { label: "Shopping",   color: "#b690e0", icon: "🛍️" },
  market:    { label: "Market",     color: "#e8924a", icon: "🏮" },
  food:      { label: "Food",       color: "#e76f6f", icon: "🍜" },
  cafe:      { label: "Café / Sweet",color: "#e89bbd", icon: "☕" },
  landmark:  { label: "Landmark",   color: "#4cc4a3", icon: "🗿" },
  transport: { label: "Transport",  color: "#8aa0b0", icon: "✈️" },
  hotel:     { label: "Stay",       color: "#6ba8e6", icon: "🏨" },
};

/* Each day = ordered stops. `kind` for food column items kept inline so
   the map + timeline tell one continuous story. */
const DAYS = [
  {
    day: 1, dateISO: "2026-11-14", weekday: "Sat", city: "Bangkok",
    theme: "Malls, Markets & a Sweet Welcome",
    blurb: "Ease into Bangkok with a weekend-only mega market, two landmark malls and the city's most famous dessert.",
    stops: [
      { name: "Chatuchak Weekend Market", cat: "market", time: "3 hours", lat: 13.7999, lng: 100.5505,
        desc: "One of the world's largest markets — 15,000+ stalls of clothes, crafts, plants, vintage and street food. Weekends only.",
        tip: "Go right at opening (~9am) to beat the heat and crowds. Bring cash and wear light clothing. MRT Kamphaeng Phet, Exit 2." },
      { name: "Siam Paragon", cat: "shopping", time: "2.5 hours", lat: 13.7463, lng: 100.5343,
        desc: "Upscale flagship mall: luxury brands, the vast Gourmet Market food hall and SEA LIFE aquarium downstairs.",
        tip: "Directly on BTS Siam. Pair it with the connected Siam Center / Siam Discovery for a full mall loop." },
      { name: "After You (Siam Paragon)", cat: "cafe", time: "1 hour", lat: 13.7461, lng: 100.5347,
        desc: "Thailand's cult dessert café — Shibuya honey toast and silky kakigori shaved ice.",
        tip: "Expect a queue. The Mango Sticky Rice kakigori is the move in mango season." },
      { name: "Terminal 21 Asok", cat: "shopping", time: "1.5 hours", lat: 13.7378, lng: 100.5602,
        desc: "Each floor themed as a world city (Paris, Tokyo, Istanbul, San Francisco). Great photo ops and a famously cheap food court.",
        tip: "Pier 21 food court on Level 5 — proper Thai dishes for ~50–80 THB. BTS Asok / MRT Sukhumvit." },
      { name: "Kanom Siam", cat: "food", time: "30 mins", lat: 13.7455, lng: 100.5340, approx: true,
        desc: "Traditional Thai sweets & snacks ('kanom') — a nostalgic bite to close the day.",
        tip: "Confirm the exact branch on Google Maps the morning of — locations vary." },
    ],
  },
  {
    day: 2, dateISO: "2026-11-15", weekday: "Sun", city: "Samut Prakan",
    theme: "Ancient Wonders",
    blurb: "Head south to the open-air museum shaped like Thailand itself, the three-headed elephant, then back for fashion bargains.",
    stops: [
      { name: "Ancient City (Muang Boran)", cat: "landmark", time: "3.5 hours", lat: 13.5396, lng: 100.6447,
        desc: "The world's largest open-air museum — 100+ replica monuments laid out in the shape of Thailand across 200 acres.",
        tip: "Allow a half-day. Rent a bicycle or golf cart on site; bring sun protection and water. ~1hr drive from central Bangkok — use Grab or a hired car." },
      { name: "Lunch — Thai food near Ancient City", cat: "food", time: "1 hour", lat: 13.5450, lng: 100.6400, approx: true,
        desc: "A relaxed local Thai lunch between the two attractions.",
        tip: "There are riverside seafood spots near Samut Prakan — ask your driver for a local favourite." },
      { name: "Erawan Museum", cat: "landmark", time: "1.5 hours", lat: 13.6075, lng: 100.6012,
        desc: "A colossal three-headed bronze elephant atop an ornate hall with a dazzling stained-glass interior and spiral staircase.",
        tip: "On the way back toward the city. Combine with Ancient City — same ticket family, same direction." },
      { name: "Pratunam Market", cat: "market", time: "2.5 hours", lat: 13.7522, lng: 100.5403,
        desc: "Wholesale fashion district — Platinum Fashion Mall plus dense street stalls. Buy 3+ pieces for wholesale pricing.",
        tip: "Best in the evening when it cools down. Haggle politely. Near Erawan Shrine & Central World for dinner." },
    ],
  },
  {
    day: 3, dateISO: "2026-11-16", weekday: "Mon", city: "Bangkok",
    theme: "Temple Trail & Riverside",
    blurb: "A grand temple circuit across the river, a Michelin chicken-rice lunch, and a feast at Central World.",
    stops: [
      { name: "Wat Arun", cat: "temple", time: "1.5 hours", lat: 13.7437, lng: 100.4887,
        desc: "The Temple of Dawn — a soaring porcelain-encrusted prang on the Chao Phraya's west bank. Iconic at sunrise and sunset.",
        tip: "Cross on the 5 THB ferry from Tha Tien pier. Climb the steep central steps for the view. Modest dress required." },
      { name: "Wat Paknam", cat: "temple", time: "1 hour", lat: 13.7088, lng: 100.4690,
        desc: "Home to a giant green Buddha and a breathtaking emerald glass stupa ceiling painted with a cosmic mandala.",
        tip: "Take the lift to the top floor for the famous green dome. One of Bangkok's most photogenic interiors." },
      { name: "Wat Khun Chan", cat: "temple", time: "45 mins", lat: 13.7140, lng: 100.4790, approx: true,
        desc: "A large reclining/seated Buddha in Thonburi, quieter and close to Wat Paknam — easy to pair.",
        tip: "Bundle with Wat Paknam in the same Thonburi loop to save backtracking." },
      { name: "Thao Maha Brahma (Erawan Shrine)", cat: "temple", time: "45 mins", lat: 13.7442, lng: 100.5403,
        desc: "The four-faced Brahma shrine at Ratchaprasong — locals come to make wishes; resident dancers perform paid blessings.",
        tip: "Right beside Central World and Big C. Buy a flower-garland-and-incense set at the gate to offer." },
      { name: "Go-Ang Pratunam Chicken Rice", cat: "food", time: "1 hour", lat: 13.7517, lng: 100.5408,
        desc: "The legendary 'pink shirt' Hainanese chicken rice — Michelin Bib Gourmand. Tender poached chicken, fragrant fat rice, fiery ginger-chilli sauce.",
        tip: "Lunch here. The pink-uniform branch is the original; expect a line that moves fast." },
      { name: "Central World", cat: "shopping", time: "2.5 hours", lat: 13.7466, lng: 100.5396,
        desc: "One of the largest shopping complexes in the world — endless dining and your dinner base tonight.",
        tip: "Dinner picks below are all in/around CentralWorld: Karun, Yaowarat Toasted Bun, The Place 168 Tom Yam." },
      { name: "Karun (CentralWorld)", cat: "cafe", time: "30 mins", lat: 13.7468, lng: 100.5392,
        desc: "Beloved Thai tea & dessert house — order the Thai milk tea and a slice of cake.",
        tip: "A sweet pre- or post-dinner stop inside the complex." },
      { name: "Yaowarat Tasty Toasted Bun", cat: "food", time: "30 mins", lat: 13.7466, lng: 100.5398,
        desc: "Chinatown-style charcoal-toasted buns with custard, taro and condensed-milk fillings.",
        tip: "Great cheap snack — grab a few flavours to share." },
      { name: "The Place 168 Giant Tom Yam", cat: "food", time: "1 hour", lat: 13.7460, lng: 100.5401, approx: true,
        desc: "Big, bold tom yum kung packed with river prawns — the dinner centrepiece near CentralWorld.",
        tip: "Order the creamy (nam khon) version if you like it rich." },
    ],
  },
  {
    day: 4, dateISO: "2026-11-17", weekday: "Tue", city: "Chiang Rai",
    theme: "North Bound",
    blurb: "A morning temple before flying north to Chiang Rai — the giant white Guanyin, a riverside dinner, and the night bazaar.",
    stops: [
      { name: "Wat Welunaram", cat: "temple", time: "45 mins", lat: 13.7200, lng: 100.4900, approx: true,
        desc: "A morning temple visit before heading to the airport.",
        tip: "Pin the exact temple in Google Maps the night before and build the airport departure around it." },
      { name: "Flight: Bangkok → Chiang Rai (CEI)", cat: "transport", time: "~1h20 flight", lat: 19.9526, lng: 99.8829,
        desc: "~1h20 flight to Mae Fah Luang–Chiang Rai International Airport. Carriers: Thai AirAsia, Thai Lion, Thai Vietjet, Nok, THAI.",
        tip: "Pack an overnight bag — you return to Bangkok tomorrow. Book this and tomorrow's return flight early for the best fares." },
      { name: "Chiang Rai Hotel — check in", cat: "hotel", time: "30 mins", lat: 19.9070, lng: 99.8310, approx: true,
        desc: "Drop bags and freshen up before the afternoon temple run.",
        tip: "Stay near the clock tower / night bazaar for easy evening walks." },
      { name: "Wat Huay Pla Kang", cat: "temple", time: "1.5 hours", lat: 19.9745, lng: 99.8198,
        desc: "A 90m white Guanyin (Goddess of Mercy) statue, a nine-tier dragon pagoda and hilltop views over Chiang Rai.",
        tip: "Take the lift up inside the Guanyin statue. Go late afternoon for softer light and cooler air." },
      { name: "Lalita Cafe", cat: "cafe", time: "1 hour", lat: 19.9000, lng: 99.8250, approx: true,
        desc: "A leafy, lantern-lit café for an early dinner / coffee after the temple.",
        tip: "Lovely at golden hour — confirm closing time, northern cafés often close early." },
      { name: "Chiang Rai Night Bazaar", cat: "market", time: "2 hours", lat: 19.9047, lng: 99.8349,
        desc: "Hill-tribe crafts, souvenirs, a buzzing food court and live music in the central square.",
        tip: "Eat at the open-air food court; catch the evening dance/music show. Cash is king here." },
    ],
  },
  {
    day: 5, dateISO: "2026-11-18", weekday: "Wed", city: "Chiang Rai",
    theme: "Temples of Colour",
    blurb: "The surreal White Temple and vivid Blue Temple, a bowl of khao soi, then a flight back to Bangkok and night shopping.",
    stops: [
      { name: "White Temple (Wat Rong Khun)", cat: "temple", time: "1.5 hours", lat: 19.8243, lng: 99.7634,
        desc: "Artist Chalermchai Kositpipat's dazzling all-white, mirror-studded temple — a surreal masterpiece with a famous 'hands of desire' bridge.",
        tip: "Open ~8am — arrive early to beat tour buses. Strict modest dress. ~15 min south of the city centre." },
      { name: "Blue Temple (Wat Rong Suea Ten)", cat: "temple", time: "1 hour", lat: 19.9293, lng: 99.8409,
        desc: "The 'Temple of the Dancing Tiger' — electric sapphire-blue interiors around a luminous white Buddha.",
        tip: "Pairs naturally with the White Temple. Stunning detail — give yourself time for photos." },
      { name: "Khao Soi lunch", cat: "food", time: "1 hour", lat: 19.9080, lng: 99.8330, approx: true,
        desc: "Northern Thailand's signature dish — golden coconut curry noodles with crispy noodles on top, pickled mustard greens and lime.",
        tip: "A Chiang Rai must-eat. Pho Chai and Khao Soi Phor Jai are local favourites." },
      { name: "Coffee", cat: "cafe", time: "30 mins", lat: 19.9060, lng: 99.8300, approx: true,
        desc: "Chiang Rai sits in prime Doi-grown coffee country — a great spot for a single-origin brew.",
        tip: "Northern Thai arabica is excellent; pick a café near your lunch stop." },
      { name: "Flight: Chiang Rai → Bangkok", cat: "transport", time: "~1h20 flight", lat: 19.9526, lng: 99.8829,
        desc: "Afternoon/evening flight back to Bangkok (~1h20).",
        tip: "Leave buffer for airport return + check-in. Re-check your Bangkok hotel arrangements." },
      { name: "Pratunam Market", cat: "market", time: "2 hours", lat: 13.7522, lng: 100.5403,
        desc: "Back in Bangkok — late-evening fashion shopping if energy allows.",
        tip: "Open late. A relaxed end to a long travel day." },
    ],
  },
  {
    day: 6, dateISO: "2026-11-19", weekday: "Thu", city: "Bangkok",
    theme: "Riverside Glamour",
    blurb: "A luxe riverfront mall, a boat-shaped temple, Michelin noodles and a dinner cruise from Asiatique.",
    stops: [
      { name: "Icon Siam", cat: "shopping", time: "3 hours", lat: 13.7264, lng: 100.5099,
        desc: "Spectacular riverside megamall with SookSiam — an indoor 'floating market' of regional Thai food — plus a nightly fountain show.",
        tip: "Take the free Icon Siam shuttle boat from BTS Saphan Taksin / Sathorn pier." },
      { name: "Pang Cha (Icon Siam)", cat: "cafe", time: "45 mins", lat: 13.7263, lng: 100.5102,
        desc: "Morning coffee & the famous mountain of Thai-tea shaved ice.",
        tip: "Order the signature Thai tea bingsu to share — it's huge." },
      { name: "Wat Yannawa", cat: "temple", time: "1 hour", lat: 13.7196, lng: 100.5146,
        desc: "A unique Chinese-junk-shaped temple commissioned by Rama III, right by Saphan Taksin.",
        tip: "Quick and quiet; pairs with the riverside route between Icon Siam and lunch." },
      { name: "Kuay Jab Mr Joe", cat: "food", time: "45 mins", lat: 13.7235, lng: 100.5135, approx: true,
        desc: "Michelin-listed kuay jab — peppery rolled rice-noodle soup with crispy pork belly and a soft egg.",
        tip: "Lunch here. Cash; can sell out. Add extra crispy pork." },
      { name: "Terminal 21 Rama 3", cat: "shopping", time: "2 hours", lat: 13.6887, lng: 100.5418,
        desc: "The newer, larger themed Terminal 21 — same world-cities concept, by the river.",
        tip: "An easy air-conditioned afternoon before the cruise." },
      { name: "Asiatique The Riverfront", cat: "landmark", time: "3 hours", lat: 13.7045, lng: 100.5025,
        desc: "Riverside night bazaar with a giant Ferris wheel, warehouses of shops and the departure point for dinner cruises.",
        tip: "Pre-book the dinner cruise. Free shuttle boat from Saphan Taksin from ~4pm. Arrive before sunset for the skyline." },
    ],
  },
  {
    day: 7, dateISO: "2026-11-20", weekday: "Fri", city: "Bangkok",
    theme: "Golden Heights & Night Market",
    blurb: "Climb the Golden Mount, stock up on snacks and skincare, then feast at one of Bangkok's hottest night markets.",
    stops: [
      { name: "Wat Saket (Golden Mount)", cat: "temple", time: "1.5 hours", lat: 13.7537, lng: 100.5068,
        desc: "A golden chedi atop an artificial hill — ~300 gentle steps wind up past bells and prayer flags to a 360° city panorama.",
        tip: "Go in the cooler morning. The climb is easy and shaded. Great rooftop views of old Bangkok." },
      { name: "Lunch (spot TBD)", cat: "food", time: "1 hour", lat: 13.7530, lng: 100.5075, approx: true,
        desc: "Open slot — your sheet left this one undecided. Old-town options near Wat Saket are excellent.",
        tip: "Nearby gems: Jay Fai (Michelin crab omelette, long queue), Thip Samai pad thai, or the Phra Nakhon street-food lanes." },
      { name: "Tofu Skin Care", cat: "shopping", time: "1 hour", lat: 13.7466, lng: 100.5396, approx: true,
        desc: "Skincare & beauty shopping — stock up on Thai and K-beauty finds.",
        tip: "Confirm the branch/mall on Google Maps; pair it with Big C nearby." },
      { name: "Big C", cat: "shopping", time: "2 hours", lat: 13.7466, lng: 100.5400,
        desc: "Hypermarket souvenir run — dried mango, Pocky, Koh-Kae nuts, snacks, sauces and gifts at local prices.",
        tip: "The Ratchadamri branch is across from CentralWorld. Best-value edible souvenirs in the city." },
      { name: "Jodd Fair (Rama 9)", cat: "market", time: "2.5 hours", lat: 13.7577, lng: 100.5663,
        desc: "Bangkok's trendiest night market — neon stalls, cocktails and the viral Leng Saap (giant volcano of pork-spine soup).",
        tip: "Dinner here. Go after dark when it's buzzing. MRT Phra Ram 9. Try the Leng Saap and grilled seafood." },
    ],
  },
  {
    day: 8, dateISO: "2026-11-21", weekday: "Sat", city: "Bangkok",
    theme: "Departure",
    blurb: "Last bites, last baht, and the journey home.",
    stops: [
      { name: "Return to BKK Airport", cat: "transport", time: "3 hours", lat: 13.6900, lng: 100.7501,
        desc: "Head to the airport for the flight home (Suvarnabhumi BKK shown; adjust if departing Don Mueang DMK).",
        tip: "Allow 3 hours before an international flight. Airport Rail Link or Grab from the city; build in buffer for traffic." },
    ],
  },
];

/* Curated food highlights for the dedicated guide section */
const FOOD_HIGHLIGHTS = [
  { name: "Go-Ang Pratunam Chicken Rice", city: "Bangkok", tag: "Michelin Bib", emoji: "🍗",
    note: "The 'pink shirt' Hainanese chicken rice — silky chicken, fat-cooked rice, killer ginger sauce." },
  { name: "Khao Soi", city: "Chiang Rai", tag: "Northern classic", emoji: "🍜",
    note: "Golden coconut-curry noodles topped with crispy noodles — the signature dish of the north." },
  { name: "Kuay Jab Mr Joe", city: "Bangkok", tag: "Michelin", emoji: "🐷",
    note: "Peppery rolled rice-noodle soup with crispy pork belly and a runny egg." },
  { name: "Leng Saap @ Jodd Fair", city: "Bangkok", tag: "Viral", emoji: "🌶️",
    note: "A towering 'volcano' of spicy pork-spine soup — the dish that made Jodd Fair famous." },
  { name: "After You", city: "Bangkok", tag: "Dessert", emoji: "🍧",
    note: "Shibuya honey toast and kakigori shaved ice — Thailand's cult sweet spot." },
  { name: "The Place 168 Giant Tom Yam", city: "Bangkok", tag: "River prawns", emoji: "🦐",
    note: "Big bowls of tom yum kung loaded with plump river prawns near CentralWorld." },
];

/* Concierge knowledge cards */
const TIPS = [
  { icon: "🌤️", title: "Weather in November",
    body: "You've timed it well — November starts Thailand's cool, dry season. Bangkok runs warm and humid (24–33°C) with little rain. Chiang Rai mornings can dip to ~17–19°C, so pack one light layer for the north." },
  { icon: "👕", title: "Temple dress code",
    body: "Cover shoulders and knees at every temple (Wat Arun, the White Temple and Blue Temple enforce it). Carry a light scarf or sarong, wear slip-off shoes, and never point your feet toward a Buddha image." },
  { icon: "🚇", title: "Getting around",
    body: "Central Bangkok: BTS Skytrain + MRT beat the traffic. Use the Grab app for door-to-door and the Chao Phraya boats for riverside temples & Icon Siam. In Chiang Rai, use Grab, a hired driver, or songthaews for the temple loop." },
  { icon: "✈️", title: "The Chiang Rai hop",
    body: "Days 4–5 are a Bangkok⇄Chiang Rai (CEI) round trip (~1h20 each way). Book both legs early, fly carry-on, and leave the bulk of your luggage at the Bangkok hotel — you're back the next night." },
  { icon: "💵", title: "Money & payments",
    body: "Currency is Thai Baht (฿). Markets, temples and street food are cash-only; malls and many cafés take card or PromptPay QR. Foreign-card ATMs charge ~220 THB per withdrawal, so take out larger amounts at once." },
  { icon: "📱", title: "Connectivity & apps",
    body: "Grab a tourist eSIM/SIM (AIS or TrueMove) at the airport. Essential apps: Grab (rides + food), Google Maps, and your bank/Wise for QR payments." },
  { icon: "🦟", title: "Stay comfortable",
    body: "Drink bottled water, wear sunscreen, and bring mosquito repellent for open-air sites like Ancient City and evening markets. A small umbrella doubles for sun and the rare shower." },
  { icon: "🕐", title: "Timing the highlights",
    body: "Chatuchak & the White Temple: arrive at opening. Wat Arun: late afternoon into sunset. Markets & Jodd Fair: after dark. This itinerary already front-loads the heat-sensitive spots in the morning." },
];

/* Interactive packing checklist (persisted in localStorage) */
const PACKING = [
  "Passport (6+ months validity)",
  "THB cash + travel card",
  "Power adapter (Type A/B/C, 220V)",
  "Light, breathable clothing",
  "Modest temple outfit / scarf / sarong",
  "Comfortable walking shoes (slip-on)",
  "Light layer for Chiang Rai mornings",
  "Sunscreen & sunglasses",
  "Mosquito repellent",
  "Reusable water bottle",
  "eSIM / tourist SIM",
  "Medications & basic first aid",
  "Small umbrella / poncho",
  "Overnight bag for the Chiang Rai hop",
];
